/** CIPP/US study content aligned with IAPP Body of Knowledge domains */

export const DOMAINS = [
  {
    id: "I",
    title: "Introduction to the U.S. Privacy Environment",
    shortTitle: "U.S. Privacy Environment",
    weight: "27–35%",
    weightNum: 31,
    description: "U.S. legal structure, enforcement, privacy programs, notices, vendor management, and international transfers.",
  },
  {
    id: "II",
    title: "Limits on Private-Sector Collection and Use of Data",
    shortTitle: "Private-Sector Limits",
    weight: "15–25%",
    weightNum: 20,
    description: "FTC, HIPAA, GLBA, FERPA, COPPA, FCRA, and sector-specific rules.",
  },
  {
    id: "III",
    title: "Government and Court Access to Private-Sector Information",
    shortTitle: "Government Access",
    weight: "3–7%",
    weightNum: 5,
    description: "Wiretaps, stored communications, national security, civil discovery, and litigation.",
  },
  {
    id: "IV",
    title: "Workplace Privacy",
    shortTitle: "Workplace Privacy",
    weight: "3–7%",
    weightNum: 5,
    description: "Employee monitoring, background checks, drug testing, and employment-related privacy laws.",
  },
  {
    id: "V",
    title: "State Privacy Laws",
    shortTitle: "State Privacy Laws",
    weight: "30–40%",
    weightNum: 35,
    description: "Breach notification, state comprehensive privacy laws, consumer rights, and enforcement.",
  },
];

export const EXAM_INFO = {
  questions: 90,
  durationMinutes: 150,
  passingScore: 300,
  maxScore: 500,
};

export const FLASHCARDS = [
  { id: "fc-1", domain: "I", front: "What are the three branches of the U.S. federal government?", back: "Legislative (Congress), Executive (President and agencies), and Judicial (federal courts). Privacy law can originate from statutes, agency rules, executive orders, and court decisions." },
  { id: "fc-2", domain: "I", front: "What is the difference between criminal and civil liability in privacy enforcement?", back: "Criminal liability may involve prosecution by the government and penalties such as imprisonment or fines. Civil liability typically involves lawsuits or agency actions seeking damages, injunctions, or civil penalties." },
  { id: "fc-3", domain: "I", front: "What is a data inventory in a privacy program?", back: "A systematic catalog of what personal data the organization collects, where it comes from, how it flows, who has access, retention periods, and legal bases for processing." },
  { id: "fc-4", domain: "I", front: "What is Schrems II and why does it matter for U.S. companies?", back: "EU Court of Justice decision invalidating Privacy Shield. Transfers of EU personal data to the U.S. require appropriate safeguards (e.g., Standard Contractual Clauses plus transfer impact assessments)." },
  { id: "fc-5", domain: "I", front: "What does FACTA require regarding data disposal?", back: "The Fair and Accurate Credit Transactions Act requires reasonable policies and procedures to protect against unauthorized access to consumer information derived from consumer reports, including secure disposal." },
  { id: "fc-6", domain: "II", front: "What is the FTC's primary legal authority for privacy enforcement?", back: "Section 5 of the FTC Act prohibits unfair or deceptive acts or practices in commerce. The FTC uses this for privacy and security enforcement when companies fail to honor privacy promises or use unfair practices." },
  { id: "fc-7", domain: "II", front: "What does COPPA protect?", back: "Children's Online Privacy Protection Act regulates operators of websites/services directed to children under 13 (or with actual knowledge of collecting from children under 13). Requires parental consent before collecting personal information." },
  { id: "fc-8", domain: "II", front: "Who are covered entities under HIPAA?", back: "Health plans, healthcare clearinghouses, and healthcare providers who transmit health information electronically in connection with standard transactions." },
  { id: "fc-9", domain: "II", front: "What are the main HIPAA Privacy Rule individual rights?", back: "Right to access, amend, accounting of disclosures, request restrictions, confidential communications, and receive a Notice of Privacy Practices." },
  { id: "fc-10", domain: "II", front: "What does GLBA require of financial institutions?", back: "Gramm-Leach-Bliley Act requires privacy notices, opt-out rights for sharing with non-affiliated third parties, and safeguards for customer information security." },
  { id: "fc-11", domain: "II", front: "What is the FCRA and who enforces it?", back: "Fair Credit Reporting Act regulates consumer reporting agencies and users of consumer reports. Enforced primarily by FTC, CFPB, and private litigation in some cases." },
  { id: "fc-12", domain: "II", front: "What does FERPA protect?", back: "Family Educational Rights and Privacy Act protects the privacy of student education records at schools receiving federal funding. Parents/eligible students have rights to access and amend records." },
  { id: "fc-13", domain: "II", front: "What is the Red Flags Rule?", back: "Requires certain financial institutions and creditors to develop identity theft prevention programs to detect, prevent, and mitigate identity theft in covered accounts." },
  { id: "fc-14", domain: "III", front: "What is the Electronic Communications Privacy Act (ECPA)?", back: "Federal law governing government access to wire, oral, and electronic communications. Includes the Wiretap Act, Stored Communications Act (SCA), and Pen Register/Trap and Trace provisions." },
  { id: "fc-15", domain: "III", front: "What does the Stored Communications Act (SCA) regulate?", back: "Government access to stored wire and electronic communications and transaction records held by third-party providers (e.g., email, cloud storage). Different standards apply depending on how long content has been stored." },
  { id: "fc-16", domain: "III", front: "What is a National Security Letter (NSL)?", back: "Administrative subpoena issued by FBI and certain agencies to telecommunications, financial, and consumer reporting companies for subscriber and transactional records in national security investigations." },
  { id: "fc-17", domain: "III", front: "What is the USA PATRIOT Act Section 215 relevance?", back: "Business records provision (FISA) allowing FBI to request records for foreign intelligence investigations; subject to FISA Court oversight and reforms after public scrutiny." },
  { id: "fc-18", domain: "IV", front: "What does the ECPA generally allow employers regarding employee communications?", back: "Employers may monitor employee communications on employer-provided systems in many circumstances, subject to notice, policy, and state law limitations." },
  { id: "fc-19", domain: "IV", front: "What does the Fair Credit Reporting Act require for employment background checks?", back: "Employers must provide notice and obtain written authorization before obtaining a consumer report; must provide pre-adverse action notice and copy of report; follow adverse action procedures." },
  { id: "fc-20", domain: "IV", front: "What is the Genetic Information Nondiscrimination Act (GINA)?", back: "Prohibits employers and health plans from using genetic information in employment and health insurance decisions. Limits employer requests for genetic information." },
  { id: "fc-21", domain: "V", front: "What is a private right of action in state privacy law?", back: "Allows individuals (or classes) to sue directly for violations, rather than relying solely on regulator enforcement. Availability varies by state and statute (e.g., some CCPA provisions, BIPA in Illinois)." },
  { id: "fc-22", domain: "V", front: "What are common elements of state data breach notification laws?", back: "Definition of personal information, trigger (acquisition of unencrypted data by unauthorized person), timing of notice to individuals and regulators, content requirements, and exceptions." },
  { id: "fc-23", domain: "V", front: "What consumer rights are common in state comprehensive privacy laws?", back: "Right to know/access, delete, correct, opt out of sale/sharing/targeted advertising, limit use of sensitive data, and non-discrimination for exercising rights." },
  { id: "fc-24", domain: "V", front: "What is the California Consumer Privacy Act (CCPA) as amended by CPRA?", back: "Comprehensive state privacy law granting California residents rights over personal information, requiring privacy notices, opt-outs, data minimization principles, and establishing the California Privacy Protection Agency." },
  { id: "fc-25", domain: "V", front: "What is a Data Protection Assessment (DPA) under many state laws?", back: "Risk assessment required for certain high-risk processing activities (e.g., targeted advertising, sale of PI, profiling with legal effects, sensitive data processing) documenting benefits vs. risks." },
  { id: "fc-26", domain: "V", front: "What is the Illinois Biometric Information Privacy Act (BIPA)?", back: "Requires informed written consent before collecting biometric identifiers, retention schedule and destruction guidelines, and prohibits profiting from biometrics. Includes private right of action." },
  { id: "fc-27", domain: "II", front: "What is HITECH's significance for HIPAA?", back: "Health Information Technology for Economic and Clinical Health Act strengthened HIPAA enforcement, extended obligations to business associates, and introduced breach notification requirements for covered entities and BAs." },
  { id: "fc-28", domain: "II", front: "What is CAN-SPAM?", back: "Controlling the Assault of Non-Solicited Pornography And Marketing Act sets rules for commercial email: accurate header info, opt-out mechanism, identification as ad, and physical address." },
  { id: "fc-29", domain: "I", front: "What is the purpose of a privacy notice?", back: "To inform individuals about what personal data is collected, how it is used, shared, retained, and what choices/rights they have. Must be accurate; FTC treats false notices as deceptive." },
  { id: "fc-30", domain: "V", front: "What is a cure period in state privacy enforcement?", back: "A window after notice of violation during which a business may fix the issue before penalties apply. Availability and duration vary by state (e.g., some laws offer 30–90 day cure rights)." },
  { id: "fc-31", domain: "II", front: "What is TCPA?", back: "Telephone Consumer Protection Act restricts telemarketing calls, auto-dialed calls, prerecorded messages, and fax ads. Requires consent for many calls/texts to cell phones." },
  { id: "fc-32", domain: "I", front: "What is APEC Cross-Border Privacy Rules (CBPR)?", back: "APEC framework for accountability-based cross-border data transfer certification among participating economies; voluntary certification program for organizations." },
  { id: "fc-33", domain: "III", front: "What is the third-party doctrine?", back: "Legal principle that individuals lack Fourth Amendment protection in information voluntarily shared with third parties. Evolving case law (e.g., Carpenter) limits application to certain digital records." },
  { id: "fc-34", domain: "V", front: "What is Washington's My Health My Data Act (MHMD)?", back: "State law regulating consumer health data not covered by HIPAA, including broad definition of consumer health data, consent requirements, geofencing restrictions near health facilities, and private right of action in some cases." },
  { id: "fc-35", domain: "II", front: "What is web scraping from a privacy law perspective?", back: "Automated collection of data from websites may implicate CFAA, trespass, contract (Terms of Service), copyright, and state privacy laws depending on data type, consent, and use." },
  // Domain I — U.S. Privacy Environment (expanded)
  { id: "fc-36", domain: "I", front: "What is common law privacy tort 'intrusion upon seclusion'?", back: "Intentional intrusion into another's private affairs or seclusion that would be highly offensive to a reasonable person. Requires actual intrusion, not merely publication." },
  { id: "fc-37", domain: "I", front: "What is the tort of 'public disclosure of private facts'?", back: "Publishing highly offensive private information about a person that is not of legitimate public concern. Truth is not a defense if the disclosure is highly offensive and not newsworthy." },
  { id: "fc-38", domain: "I", front: "What is 'false light' as a privacy tort?", back: "Publicity placing a person in a false light that would be highly offensive and the publisher acted with reckless disregard of falsity. Similar to defamation but focuses on misleading impression." },
  { id: "fc-39", domain: "I", front: "What is the right of publicity?", back: "Protects against unauthorized commercial use of a person's name, likeness, or identity. Varies by state; some treat it as property right, others as privacy tort." },
  { id: "fc-40", domain: "I", front: "What is the difference between statutes and regulations?", back: "Statutes are laws enacted by legislatures. Regulations are rules issued by agencies under delegated authority to implement statutes. Both can create binding privacy obligations." },
  { id: "fc-41", domain: "I", front: "What role do state attorneys general play in privacy enforcement?", back: "State AGs enforce state consumer protection, breach notification, and comprehensive privacy laws. They may investigate, sue, and seek injunctions and penalties. Some coordinate multistate actions." },
  { id: "fc-42", domain: "I", front: "What is accountability in a privacy program?", back: "Demonstrating responsibility for privacy through governance, policies, training, audits, documentation, and mechanisms to show compliance with laws and internal standards." },
  { id: "fc-43", domain: "I", front: "What is a Record of Processing Activities (ROPA) under GDPR—and why do U.S. multinationals care?", back: "GDPR requires documenting processing activities. U.S. multinationals subject to GDPR must maintain ROPAs even for U.S. operations processing EU data, supporting accountability and transfer compliance." },
  { id: "fc-44", domain: "I", front: "What are Standard Contractual Clauses (SCCs)?", back: "EU-approved contractual terms for transferring personal data to third countries. Post-Schrems II, organizations must assess whether supplementary measures are needed for U.S. transfers." },
  { id: "fc-45", domain: "I", front: "What was the EU-U.S. Data Privacy Framework (successor to Privacy Shield)?", back: "Framework providing adequacy for U.S. transfers when organizations self-certify with commitments (e.g., redress mechanisms). Organizations should monitor legal challenges and supplement as needed." },
  { id: "fc-46", domain: "I", front: "What is data minimization?", back: "Collecting only personal data that is adequate, relevant, and limited to what is necessary for stated purposes. Increasingly required or encouraged under state laws and FTC guidance." },
  { id: "fc-47", domain: "I", front: "What is purpose limitation?", back: "Using personal data only for purposes disclosed at collection or compatible purposes, unless further notice and consent (where required) are obtained." },
  { id: "fc-48", domain: "I", front: "What should an incident response program include?", back: "Detection, containment, investigation, notification (legal/regulatory/individual), remediation, documentation, and post-incident review. Must align with breach laws and contractual obligations." },
  { id: "fc-49", domain: "I", front: "What is a Data Processing Agreement (DPA)?", back: "Contract between controller and processor defining processing instructions, security, subprocessors, breach notification, audits, and return/deletion of data. Required under GDPR and many state laws." },
  { id: "fc-50", domain: "I", front: "What is the California Online Privacy Protection Act (CalOPPA)?", back: "Requires operators of commercial websites collecting PII from California consumers to post privacy policies conspicuously, including categories collected and how to contact the operator." },
  { id: "fc-51", domain: "I", front: "What is managing user preferences in a privacy program?", back: "Honoring opt-outs, cookie choices, marketing preferences, and rights requests through consistent technical and operational controls across channels." },
  { id: "fc-52", domain: "I", front: "What is privacy by design?", back: "Integrating privacy into the design of systems, products, and processes from the outset rather than bolting on later—defaults, minimization, security, transparency." },
  { id: "fc-53", domain: "I", front: "What is the role of the FTC in online privacy?", back: "Enforces Section 5 against deceptive privacy practices and unfair security practices; enforces COPPA, CAN-SPAM, FCRA (with others), and brings actions for broken promises in privacy policies." },
  { id: "fc-54", domain: "I", front: "What is preemption in privacy law?", back: "When federal law displaces conflicting state law. Analysis requires examining express preemption clauses, implied field preemption, and whether state law provides greater protection where permitted." },
  { id: "fc-55", domain: "I", front: "What are binding corporate rules (BCRs)?", back: "Internal rules approved by EU authorities allowing multinational groups to transfer personal data within the corporate group from the EU to affiliates in non-adequate countries." },
  { id: "fc-56", domain: "I", front: "What is a privacy impact assessment (PIA)?", back: "Systematic assessment of privacy risks of a project or system before launch, documenting data flows, risks, and mitigations. Similar to DPIA under GDPR for high-risk processing." },
  { id: "fc-57", domain: "I", front: "What is retention and disposal in privacy management?", back: "Defining how long data is kept based on business and legal needs, then securely deleting or anonymizing when no longer needed. FACTA and state laws impose specific disposal duties." },
  { id: "fc-58", domain: "I", front: "What is workforce privacy training?", back: "Educating employees on policies, lawful handling of personal data, security practices, and reporting incidents. Demonstrates accountability and reduces insider risk." },
  { id: "fc-59", domain: "I", front: "What is the difference between a controller and processor?", back: "Controller determines purposes and means of processing. Processor processes on behalf of the controller per instructions. Many U.S. companies act as both depending on context." },
  { id: "fc-60", domain: "I", front: "What are multinational compliance conflicts?", back: "Situations where laws in different jurisdictions impose incompatible requirements (e.g., EU access rights vs. U.S. secrecy laws). Resolved through legal analysis, prioritization, and documented risk decisions." },
  // Domain II — Private-Sector Limits (expanded)
  { id: "fc-61", domain: "II", front: "What is PHI under HIPAA?", back: "Protected Health Information—individually identifiable health information held or transmitted by a covered entity or business associate in any form (electronic, paper, oral), with limited exceptions." },
  { id: "fc-62", domain: "II", front: "What is a Business Associate Agreement (BAA)?", back: "Contract requiring business associates to safeguard PHI, report breaches, and comply with HIPAA Security and Privacy Rule provisions applicable to BAs." },
  { id: "fc-63", domain: "II", front: "What does the HIPAA Security Rule require?", back: "Administrative, physical, and technical safeguards to ensure confidentiality, integrity, and availability of ePHI, including risk analysis, workforce security, and access controls." },
  { id: "fc-64", domain: "II", front: "What is the minimum necessary standard under HIPAA?", back: "Covered entities and BAs must make reasonable efforts to use, disclose, and request only the minimum PHI necessary to accomplish the intended purpose." },
  { id: "fc-65", domain: "II", front: "What is the 21st Century Cures Act information blocking rule?", back: "Prohibits practices that interfere with access, exchange, or use of electronic health information, with exceptions. Promotes patient access to health data via APIs and standards." },
  { id: "fc-66", domain: "II", front: "What does the Confidentiality of Substance Use Disorder Patient Records Rule (42 CFR Part 2) protect?", back: "Restricts disclosure of substance use disorder treatment records by federally assisted programs beyond general HIPAA in many cases; requires patient consent for most disclosures." },
  { id: "fc-67", domain: "II", front: "What is nonpublic personal information (NPI) under GLBA?", back: "Personally identifiable financial information provided by a consumer to a financial institution, resulting from transactions, or obtained in connection with providing a financial product or service." },
  { id: "fc-68", domain: "II", front: "What are GLBA Safeguards Rule requirements?", back: "Financial institutions must develop, implement, and maintain a comprehensive information security program with administrative, technical, and physical safeguards appropriate to size and complexity." },
  { id: "fc-69", domain: "II", front: "What does the Fair Credit Reporting Act require of consumer reporting agencies?", back: "Maintain reasonable procedures for maximum possible accuracy, provide consumers access and dispute rights, and limit furnishing reports to permissible purposes." },
  { id: "fc-70", domain: "II", front: "What is a permissible purpose under FCRA?", back: "Statutory grounds allowing a party to obtain a consumer report, e.g., credit transactions, employment (with consent), insurance, legitimate business need. Unauthorized pulls violate FCRA." },
  { id: "fc-71", domain: "II", front: "What does the FACT Act add to FCRA?", back: "Free annual credit reports, fraud alerts, active duty alerts, truncation of card numbers on receipts, and identity theft red flag provisions." },
  { id: "fc-72", domain: "II", front: "What is the Dodd-Frank Act's relevance to privacy?", back: "Created the CFPB with authority over consumer financial protection laws including FCRA and UDAAP (unfair, deceptive, or abusive acts or practices)." },
  { id: "fc-73", domain: "II", front: "What is UDAAP?", back: "Unfair, Deceptive, or Abusive Acts or Practices—CFPB authority to pursue conduct that harms consumers, including certain privacy-related practices in financial services." },
  { id: "fc-74", domain: "II", front: "What does FERPA consider 'directory information'?", back: "Information not generally considered harmful if disclosed (e.g., name, address, dates of attendance). Schools must notify parents/students and allow opt-out of directory disclosures." },
  { id: "fc-75", domain: "II", front: "What are education technology (EdTech) privacy concerns?", back: "Schools and vendors handling student data must comply with FERPA, state student privacy laws, and vendor contracts. Schools often act as agents; agreements should limit use and require security." },
  { id: "fc-76", domain: "II", front: "What is verifiable parental consent under COPPA?", back: "Methods reasonably calculated to ensure the person giving consent is the child's parent, e.g., credit card verification, signed form, video conference, or government ID check depending on risk." },
  { id: "fc-77", domain: "II", front: "What is the Telemarketing Sales Rule (TSR)?", back: "FTC rule governing telemarketing including calling time restrictions, disclosures, prohibitions on misrepresentations, and requirements related to charitable solicitations and payment methods." },
  { id: "fc-78", domain: "II", front: "What is the CAN-SPAM opt-out requirement?", back: "Commercial email must include a clear opt-out mechanism; opt-out requests must be honored within 10 business days. Cannot require payment or excessive information to opt out." },
  { id: "fc-79", domain: "II", front: "What is the FTC's Health Breach Notification Rule?", back: "Requires vendors of personal health records and related entities not covered by HIPAA to notify consumers, FTC, and sometimes media of breaches of unsecured PHR identifiable health information." },
  { id: "fc-80", domain: "II", front: "What is the Graham-Leach-Bliley Act Financial Privacy Rule?", back: "Requires financial institutions to provide initial and annual privacy notices describing information sharing and opt-out rights for certain third-party sharing." },
  { id: "fc-81", domain: "II", front: "What is an affiliate under GLBA?", back: "Companies related by common ownership or control. Sharing among affiliates is treated differently than sharing with non-affiliated third parties for opt-out purposes." },
  { id: "fc-82", domain: "II", front: "What does the FTC consider a deceptive privacy practice?", back: "A material representation, omission, or practice likely to mislead consumers acting reasonably, including failing to honor privacy policy promises or omitting material limitations." },
  { id: "fc-83", domain: "II", front: "What does the FTC consider an unfair practice?", back: "Causes or is likely to cause substantial consumer injury not reasonably avoidable by consumers and not outweighed by benefits—often applied to unreasonable data security." },
  { id: "fc-84", domain: "II", front: "What is the Children's Online Privacy Protection Rule (COPPA Rule)?", back: "FTC rule implementing COPPA with requirements for privacy policies, parental notice, consent, data security, and limitations on conditioning participation on disclosing more data than necessary." },
  { id: "fc-85", domain: "II", front: "What is the TCPA autodialer restriction?", back: "Generally prohibits non-emergency autodialed/prerecorded calls to cell phones without prior express consent; telemarketing calls/texts often require prior express written consent." },
  // Domain III — Government Access (expanded)
  { id: "fc-86", domain: "III", front: "What does the Wiretap Act prohibit?", back: "Intentional interception of wire, oral, or electronic communications without consent or legal exception. Violations can result in criminal penalties and civil damages." },
  { id: "fc-87", domain: "III", front: "What is a pen register vs. trap and trace?", back: "Pen register captures outgoing dialing/routing information; trap and trace captures incoming. Government access requires court order under ECPA, not full wiretap warrant." },
  { id: "fc-88", domain: "III", front: "What standard applies to SCA access to email stored 180 days or less?", back: "Government generally needs a warrant based on probable cause for contents of communications in electronic storage 180 days or less (post-2016 reforms)." },
  { id: "fc-89", domain: "III", front: "What is the CLOUD Act?", back: "Clarifies U.S. law enforcement can compel U.S. providers via warrant for certain data regardless of storage location; creates framework for executive agreements with qualifying foreign governments." },
  { id: "fc-90", domain: "III", front: "What is FISA?", back: "Foreign Intelligence Surveillance Act—governs electronic surveillance and collection of foreign intelligence information, including oversight by the FISA Court for certain government requests." },
  { id: "fc-91", domain: "III", front: "What is the Carpenter v. United States holding?", back: "Government acquisition of cell-site location information from wireless carriers is a Fourth Amendment search generally requiring a warrant, limiting third-party doctrine for detailed location records." },
  { id: "fc-92", domain: "III", front: "What is civil discovery of ESI?", back: "In litigation, parties exchange relevant electronically stored information under Federal Rules of Civil Procedure, subject to privilege, proportionality, and protective orders—not SCA third-party rules." },
  { id: "fc-93", domain: "III", front: "What is the work-product doctrine?", back: "Protects materials prepared in anticipation of litigation from discovery. Privacy counsel communications may be protected when attorney-client privilege or work product applies." },
  { id: "fc-94", domain: "III", front: "What is a gag order on NSL recipients?", back: "Historically NSLs included nondisclosure provisions; reforms allow limited transparency and judicial review of gag orders. Providers must still comply with valid NSLs." },
  { id: "fc-95", domain: "III", front: "What is the All Writs Act relevance to encryption?", back: "Courts have invoked it to compel assistance in law enforcement investigations, though encryption 'going dark' debates continue; not a substitute for comprehensive privacy statutes." },
  // Domain IV — Workplace Privacy (expanded)
  { id: "fc-96", domain: "IV", front: "What does the Americans with Disabilities Act (ADA) restrict regarding medical information?", back: "Employers must keep employee medical information confidential in separate medical files, with limited exceptions for supervisors, safety personnel, and government officials on a need-to-know basis." },
  { id: "fc-97", domain: "IV", front: "What is the Fair and Accurate Credit Transactions Act (FACTA) employment relevance?", back: "Along with FCRA, governs background checks; FACTA also addresses identity theft red flags and disposal of consumer report information in employment contexts." },
  { id: "fc-98", domain: "IV", front: "What is adverse action under FCRA in hiring?", back: "After pre-adverse notice and waiting period, employer may take adverse action based on consumer report; must provide final adverse action notice with CRA contact and rights summary." },
  { id: "fc-99", domain: "IV", front: "What is the Employee Polygraph Protection Act (EPPA)?", back: "Generally prohibits private employers from using lie detector tests for employment, with limited exceptions for certain security services and ongoing investigations." },
  { id: "fc-100", domain: "IV", front: "What is the NLRA relevance to workplace monitoring?", back: "National Labor Relations Act protects concerted activity; overly broad social media or monitoring policies may violate NLRA even in non-union workplaces per NLRB guidance." },
  { id: "fc-101", domain: "IV", front: "What is bring-your-own-device (BYOD) privacy risk?", back: "Mixing personal and work data on employee devices raises monitoring, wipe, e-discovery, and notice issues; policies should clarify scope of employer access and security requirements." },
  { id: "fc-102", domain: "IV", front: "What is workplace video surveillance best practice?", back: "Notice to employees, legitimate business purpose, avoid areas with heightened privacy expectation (e.g., restrooms), comply with state wiretap/consent laws for audio." },
  { id: "fc-103", domain: "IV", front: "What does the Stored Communications Act mean for employer access to employee emails?", back: "If employer is the provider (company email system), access to stored communications may be permitted under provider exception with policy notice; third-party personal accounts have stronger protections." },
  { id: "fc-104", domain: "IV", front: "What is marijuana testing and privacy?", back: "Drug testing of employees implicates state privacy, disability, and recreational marijuana laws that increasingly restrict adverse action for off-duty lawful use." },
  { id: "fc-105", domain: "IV", front: "What is GINA's exception for acquired genetic information?", back: "Inadvertent acquisition (e.g., water cooler conversation) is not unlawful, but employers cannot use genetic information in employment decisions and should keep it confidential." },
  // Domain V — State Privacy Laws (expanded)
  { id: "fc-106", domain: "V", front: "What is 'personal information' under most state comprehensive laws?", back: "Information linked or reasonably linkable to an identified or identifiable consumer, often excluding publicly available government records and de-identified data meeting specific standards." },
  { id: "fc-107", domain: "V", front: "What is 'sale' of personal information under CCPA/CPRA?", back: "Selling, renting, releasing, disclosing, disseminating, making available, or otherwise communicating PI to another business for monetary or other valuable consideration, with statutory exceptions." },
  { id: "fc-108", domain: "V", front: "What is 'sharing' for cross-context behavioral advertising under CPRA?", back: "Disclosing PI to a third party for cross-context behavioral advertising whether or not for money—consumers have right to opt out of sharing." },
  { id: "fc-109", domain: "V", front: "What is sensitive personal information under CPRA?", back: "Includes SSN, financial account credentials, precise geolocation, racial/ethnic origin, union membership, mail/email/content, genetic data, biometric info, health data, sex life/orientation, and government ID numbers." },
  { id: "fc-110", domain: "V", front: "What is the right to limit use of sensitive PI under CPRA?", back: "Consumers can direct businesses to limit use of sensitive PI to purposes necessary to perform services reasonably expected by consumers, with notice and 'Limit' link requirements." },
  { id: "fc-111", domain: "V", front: "What is Virginia's VCDPA?", back: "Virginia Consumer Data Protection Act—comprehensive privacy law granting access, correction, deletion, portability, and opt-out rights for targeted advertising, sale, and profiling, with controller-processor contracts." },
  { id: "fc-112", domain: "V", front: "What is Colorado's CPA?", back: "Colorado Privacy Act—similar comprehensive framework with rights to access, correct, delete, portability, and opt out of targeted advertising, sale, and profiling in furtherance of decisions producing legal effects." },
  { id: "fc-113", domain: "V", front: "What is Connecticut's CTDPA?", back: "Connecticut Data Privacy Act—comprehensive state law with consumer rights, opt-outs, data protection assessments, and universal opt-out mechanism requirements via Global Privacy Control." },
  { id: "fc-114", domain: "V", front: "What is Utah's UCPA?", back: "Utah Consumer Privacy Act—business-friendly comprehensive law with consumer rights but narrower scope, no private right of action, and emphasis on opt-out for sale and targeted advertising." },
  { id: "fc-115", domain: "V", front: "What is Texas's TDPSA?", back: "Texas Data Privacy and Security Act—comprehensive law with broad applicability thresholds, consumer rights, opt-outs, and data protection assessments for certain processing." },
  { id: "fc-116", domain: "V", front: "What is Oregon's OCPA?", back: "Oregon Consumer Privacy Act—comprehensive privacy law with rights, processor obligations, DPIAs for high-risk processing, and phased effective dates." },
  { id: "fc-117", domain: "V", front: "What is Montana's MCDPA?", back: "Montana Consumer Data Privacy Act—comprehensive law with relatively low applicability threshold (e.g., 50,000 consumers) and standard consumer rights package." },
  { id: "fc-118", domain: "V", front: "What is Florida's FDBR?", back: "Florida Digital Bill of Rights—comprehensive law focused on very large technology companies and certain data practices, with consumer rights and restrictions on government requests to platforms." },
  { id: "fc-119", domain: "V", front: "What is the Global Privacy Control (GPC)?", back: "Browser/signal mechanism consumers use to opt out of sale/sharing. Several states require businesses to honor GPC as a valid opt-out request." },
  { id: "fc-120", domain: "V", front: "What is a 'service provider' under CCPA?", back: "Entity that processes PI on behalf of a business pursuant to written contract prohibiting selling/sharing PI and limiting use to specified business purposes." },
  { id: "fc-121", domain: "V", front: "What is a 'contractor' under CPRA?", back: "Person to whom a business makes available a consumer's PI for a business purpose pursuant to contract with purpose limitation, confidentiality, and no selling/sharing restrictions." },
  { id: "fc-122", domain: "V", front: "What is the California Delete Act (SB 362)?", back: "Establishes DELETE Account—a single request mechanism for consumers to direct data brokers to delete their personal information, enforced by CPPA with registration fees for data brokers." },
  { id: "fc-123", domain: "V", front: "What is Nevada's opt-out law (NRS 603A)?", back: "Requires operators to establish designated request address for consumers to opt out of sale of covered information; one of the earlier state sale opt-out statutes." },
  { id: "fc-124", domain: "V", front: "What is Nevada's consumer health data privacy law (SB 370)?", back: "Regulates consumer health data not covered by HIPAA with consent requirements, restrictions on sale, and rights similar to comprehensive laws for health-related data." },
  { id: "fc-125", domain: "V", front: "What is the Illinois Genetic Information Privacy Act (GIPA)?", back: "Restricts collection and use of genetic information by employers and others; recent class actions expanded privacy litigation beyond BIPA." },
  { id: "fc-126", domain: "V", front: "What is the California Invasion of Privacy Act (CIPA)?", back: "Wiretap statute requiring all-party consent for recording confidential communications; frequently litigated in website session replay and tracking technology cases." },
  { id: "fc-127", domain: "V", front: "What are state data broker registration laws?", back: "California, Vermont, Texas, and others require data brokers to register, disclose practices, and comply with deletion/opt-out regimes—important for third-party data sellers." },
  { id: "fc-128", domain: "V", front: "What is a 'controller' under state comprehensive laws?", back: "Entity that determines the purpose and means of processing personal data, bearing primary responsibility for rights requests, notices, and assessments." },
  { id: "fc-129", domain: "V", front: "What is a 'processor' under state comprehensive laws?", back: "Entity that processes personal data on behalf of a controller pursuant to contract with instructions, confidentiality, security, and subprocessors requirements." },
  { id: "fc-130", domain: "V", front: "What is pseudonymization vs. anonymization?", back: "Pseudonymized data can still be personal data if re-identifiable with additional information. Anonymized data cannot reasonably identify a person—often exempt if truly anonymized under state law tests." },
  { id: "fc-131", domain: "V", front: "What is geofencing in health privacy laws?", back: "Virtual perimeter around healthcare facilities; some state laws prohibit using geofencing to infer health status or target consumers entering medical facilities." },
  { id: "fc-132", domain: "V", front: "What is non-discrimination for exercising privacy rights?", back: "Businesses cannot deny goods/services, charge different prices, or provide different quality solely because a consumer exercised rights, though loyalty programs have nuanced exceptions." },
  { id: "fc-133", domain: "V", front: "What is a 'dark pattern' in privacy?", back: "Design practices that subvert or impair user autonomy and choice, e.g., confusing opt-out flows. CPRA and FTC policy discourage dark patterns in consent and rights exercise." },
  { id: "fc-134", domain: "V", front: "What is an Applicability threshold in state privacy laws?", back: "Criteria such as annual revenue, number of state residents' data processed, or percentage of revenue from selling data determining whether a business must comply." },
  { id: "fc-135", domain: "V", front: "What are common exemptions in state comprehensive laws?", back: "GLBA-covered entities, HIPAA-covered entities, FERPA, non-profits (varies), employment data (often), B2B contact data (varies), and de-identified data meeting statutory tests." },
  { id: "fc-136", domain: "V", front: "What is a privacy notice under state comprehensive laws?", back: "Disclosure at or before collection describing categories of PI, purposes, rights, categories of third parties, retention, and how to submit requests—often requires a dedicated state supplement." },
  { id: "fc-137", domain: "V", front: "What is the right to correct under state laws?", back: "Consumers may request correction of inaccurate personal data; businesses must use commercially reasonable efforts to correct and direct service providers to do the same." },
  { id: "fc-138", domain: "V", front: "What is the right to portability?", back: "Consumers receive personal data in a portable, readily usable format allowing transmission to another entity where technically feasible." },
  { id: "fc-139", domain: "V", front: "What is authentication of consumer requests?", back: "Businesses must verify requesters' identity to a reasonable degree of certainty using information matching or other methods without collecting excessive new data." },
  { id: "fc-140", domain: "V", front: "What is a 45-day response period for CCPA requests?", back: "Businesses must respond to verifiable consumer requests within 45 days, extendable by 45 additional days when reasonably necessary with notice to the consumer." },
  { id: "fc-141", domain: "V", front: "What is the role of the California Privacy Protection Agency (CPPA)?", back: "First U.S. dedicated privacy regulator with rulemaking, enforcement, and guidance authority over CCPA/CPRA, including regulations on cybersecurity audits and risk assessments." },
  { id: "fc-142", domain: "V", front: "What is Massachusetts 201 CMR 17.00?", back: "Requires persons who own/license personal information of MA residents to implement comprehensive written information security program (WISP) with administrative, technical, and physical safeguards." },
  { id: "fc-143", domain: "V", front: "What is New York SHIELD Act?", back: "Stop Hacks and Improve Electronic Data Security Act—requires reasonable safeguards for private information and breach notification for NY residents, with safe harbor for compliant regulated entities." },
  { id: "fc-144", domain: "V", front: "What is a 'security breach' under most state laws?", back: "Unauthorized acquisition of computerized data compromising security, confidentiality, or integrity of personal information. Encrypted data with compromised keys may still trigger notification." },
  { id: "fc-145", domain: "V", front: "What is AG multistate breach coordination?", back: "State attorneys general often jointly investigate large breaches, negotiate settlements requiring security improvements, credit monitoring, and penalties under state UDAP and breach laws." },
  { id: "fc-146", domain: "V", front: "What is the Children's privacy under state laws?", back: "Some states impose additional duties on processing children's data (e.g., under 13 or 16), including consent, DPIAs, and prohibitions on targeted advertising—beyond COPPA where applicable." },
  { id: "fc-147", domain: "V", front: "What is profiling under state comprehensive laws?", back: "Automated processing to evaluate personal aspects such as performance, preferences, or behavior; consumers may opt out of profiling in furtherance of decisions with legal or similarly significant effects." },
  { id: "fc-148", domain: "V", front: "What is targeted advertising under state laws?", back: "Displaying ads to consumers based on PI from activities across non-affiliated websites, apps, or services—distinct from first-party contextual advertising." },
  { id: "fc-149", domain: "V", front: "What is Iowa's SF 262 consumer privacy law?", back: "Iowa Consumer Data Protection Act—comprehensive law with consumer rights and opt-outs, effective 2025, without private right of action." },
  { id: "fc-150", domain: "V", front: "What is Indiana's INCDPA?", back: "Indiana Consumer Data Protection Act—comprehensive privacy law with standard rights, processor contracts, and data protection assessments for high-risk processing activities." },
];

export const QUIZ_QUESTIONS = [
  {
    id: "q-1",
    domain: "I",
    question: "A multinational company must transfer EU employee data to U.S. servers. After Schrems II, which approach is MOST appropriate?",
    options: [
      "Rely on the invalidated EU-U.S. Privacy Shield framework",
      "Use Standard Contractual Clauses plus a transfer impact assessment",
      "No safeguards needed if data is encrypted in transit only",
      "Obtain consent from one EU employee as representative",
    ],
    correct: 1,
    explanation: "Schrems II invalidated Privacy Shield. Organizations typically use SCCs with supplementary measures and document transfer impact assessments.",
  },
  {
    id: "q-2",
    domain: "II",
    question: "An app directed at children under 13 collects names and email without parental consent. Which law is MOST directly violated?",
    options: ["HIPAA", "COPPA", "FERPA", "GLBA"],
    correct: 1,
    explanation: "COPPA requires verifiable parental consent before collecting personal information from children under 13.",
  },
  {
    id: "q-3",
    domain: "II",
    question: "A bank shares customer account data with an unrelated marketing company without offering an opt-out. Which law is MOST relevant?",
    options: ["FCRA", "GLBA", "HIPAA", "TCPA"],
    correct: 1,
    explanation: "GLBA requires privacy notices and opt-out rights before sharing nonpublic personal information with non-affiliated third parties.",
  },
  {
    id: "q-4",
    domain: "II",
    question: "A university receiving federal funds refuses to let a parent review their minor child's education records. Which law applies?",
    options: ["COPPA", "FERPA", "GINA", "FCRA"],
    correct: 1,
    explanation: "FERPA grants parents rights to access education records of minor students at institutions receiving federal education funds.",
  },
  {
    id: "q-5",
    domain: "III",
    question: "Law enforcement seeks the contents of emails stored for 200 days with a U.S. cloud provider. Which statute primarily governs access?",
    options: ["Wiretap Act only", "Stored Communications Act", "HIPAA Security Rule", "CAN-SPAM"],
    correct: 1,
    explanation: "The SCA governs government access to stored electronic communications held by third-party providers, with different standards based on age of storage.",
  },
  {
    id: "q-6",
    domain: "IV",
    question: "Before rejecting a job applicant based on a background check, the employer must FIRST:",
    options: [
      "Delete all application materials",
      "Provide pre-adverse action notice and a copy of the report",
      "Report the applicant to the FTC",
      "Obtain a court order",
    ],
    correct: 1,
    explanation: "FCRA requires pre-adverse action disclosure including a copy of the consumer report and summary of rights before final adverse action.",
  },
  {
    id: "q-7",
    domain: "V",
    question: "A California resident wants to stop a business from selling their personal information. Under CCPA/CPRA, they may:",
    options: [
      "Only sue in federal court automatically",
      "Use the right to opt out of sale/sharing",
      "Demand the business cease all operations",
      "Require deletion of all public government records",
    ],
    correct: 1,
    explanation: "California residents have the right to opt out of the sale or sharing of personal information, with businesses required to honor requests.",
  },
  {
    id: "q-8",
    domain: "V",
    question: "Which Illinois law has driven significant class action litigation over fingerprint time clocks?",
    options: ["CCPA", "BIPA", "FERPA", "TCPA"],
    correct: 1,
    explanation: "BIPA requires consent and policies for biometric data and includes a private right of action, leading to substantial litigation.",
  },
  {
    id: "q-9",
    domain: "I",
    question: "The FTC prosecutes a company for failing to implement reasonable security after promising strong protection in its privacy policy. This is an example of:",
    options: [
      "Criminal wire fraud only",
      "Section 5 unfair or deceptive practices",
      "HIPAA breach notification",
      "State preemption",
    ],
    correct: 1,
    explanation: "FTC uses Section 5 authority for deceptive practices (broken promises) and unfair practices (unreasonable security causing harm).",
  },
  {
    id: "q-10",
    domain: "II",
    question: "A covered entity discovers unsecured PHI of 600 individuals was accessed by a hacker. Under HIPAA/HITECH, it must:",
    options: [
      "Notify only the CEO internally",
      "Notify HHS, and potentially media and individuals depending on breach size",
      "Wait five years before any notification",
      "Notify only state attorneys general",
    ],
    correct: 1,
    explanation: "HIPAA breach notification rules require notification to individuals, HHS, and in large breaches (500+ in a state), prominent media outlets.",
  },
  {
    id: "q-11",
    domain: "V",
    question: "State comprehensive privacy laws often require a Data Protection Assessment for:",
    options: [
      "All payroll processing regardless of risk",
      "High-risk processing such as targeted advertising or sensitive data",
      "Only government agencies",
      "Publicly available federal records",
    ],
    correct: 1,
    explanation: "Many state laws mandate DPAs for defined high-risk processing activities to evaluate and document privacy risks.",
  },
  {
    id: "q-12",
    domain: "III",
    question: "National Security Letters typically:",
    options: [
      "Require public disclosure by recipients in all cases",
      "Allow certain agencies to obtain specified records without full public court proceedings",
      "Only apply to healthcare providers under HIPAA",
      "Replace all state breach notification requirements",
    ],
    correct: 1,
    explanation: "NSLs are administrative requests for specified records in national security investigations, with gag order provisions historically attached.",
  },
  {
    id: "q-13",
    domain: "II",
    question: "A consumer reporting agency provides inaccurate credit data causing loan denial. The consumer's PRIMARY federal remedy is under:",
    options: ["FERPA", "FCRA", "COPPA", "CAN-SPAM"],
    correct: 1,
    explanation: "FCRA establishes duties for accuracy, dispute investigation, and remedies for consumers harmed by inaccurate reporting.",
  },
  {
    id: "q-14",
    domain: "IV",
    question: "An employer wants to use an employee's genetic test results in hiring decisions. GINA:",
    options: [
      "Permits this if the employee signs any form",
      "Generally prohibits using genetic information in employment decisions",
      "Only applies to federal government contractors",
      "Overrides all state laws without exception",
    ],
    correct: 1,
    explanation: "GINA restricts employers from using genetic information in employment decisions and limits acquisition of genetic information.",
  },
  {
    id: "q-15",
    domain: "V",
    question: "Most state data breach notification laws are triggered when:",
    options: [
      "Any employee receives a phishing email",
      "Unencrypted personal information is acquired by an unauthorized person",
      "A company updates its privacy policy",
      "A customer requests data deletion",
    ],
    correct: 1,
    explanation: "Breach laws typically define triggering events involving unauthorized acquisition of unencrypted personal information.",
  },
  {
    id: "q-16",
    domain: "I",
    question: "A privacy program data flow mapping exercise is BEST described as:",
    options: [
      "Deleting all legacy databases",
      "Documenting how personal data moves through systems, vendors, and jurisdictions",
      "Replacing all privacy notices with terms of service",
      "Eliminating the need for vendor contracts",
    ],
    correct: 1,
    explanation: "Data flow mapping visualizes collection, use, storage, transfers, and disposal—foundational for privacy program management.",
  },
  {
    id: "q-17",
    domain: "II",
    question: "TCPA violations often involve:",
    options: [
      "Unsecured HIPAA servers",
      "Auto-dialed or prerecorded calls/texts to cell phones without proper consent",
      "FERPA education record access",
      "State property tax assessments",
    ],
    correct: 1,
    explanation: "TCPA restricts telemarketing and automated calls/texts, with consent requirements especially for wireless numbers.",
  },
  {
    id: "q-18",
    domain: "V",
    question: "The California Privacy Protection Agency (CPPA) was established by:",
    options: ["HIPAA", "CPRA amendment to CCPA", "FCRA", "ECPA"],
    correct: 1,
    explanation: "CPRA (2020 ballot initiative) expanded CCPA and created the CPPA as a dedicated privacy regulator.",
  },
  {
    id: "q-19",
    domain: "II",
    question: "A business associate under HIPAA is:",
    options: [
      "Any patient",
      "An entity that performs functions involving PHI on behalf of a covered entity",
      "Only the Department of Health and Human Services",
      "A marketing affiliate of any retailer",
    ],
    correct: 1,
    explanation: "Business associates handle PHI for covered entities and must comply with HIPAA obligations via BAA.",
  },
  {
    id: "q-20",
    domain: "I",
    question: "When federal and state privacy laws conflict, the exam often tests:",
    options: [
      "State law always wins without analysis",
      "Preemption analysis—whether federal law expressly or impliedly preempts state requirements",
      "Only international treaties apply",
      "Employers may ignore both",
    ],
    correct: 1,
    explanation: "Preemption doctrine determines whether federal law displaces state law; some federal laws have express preemption clauses.",
  },
  {
    id: "q-21",
    domain: "V",
    question: "Washington's My Health My Data Act primarily addresses:",
    options: [
      "Only HIPAA-covered entities",
      "Consumer health data outside traditional HIPAA coverage",
      "Federal tax records",
      "FERPA student grades only",
    ],
    correct: 1,
    explanation: "MHMD regulates consumer health data collected by non-HIPAA-covered businesses, with consent and geofencing provisions.",
  },
  {
    id: "q-22",
    domain: "III",
    question: "In civil litigation, discovery of another party's stored emails in the other party's custody is generally governed by:",
    options: [
      "Only the Wiretap Act",
      "Civil procedure rules and relevance/privilege—not the SCA third-party provider rules",
      "COPPA exclusively",
      "State real estate law",
    ],
    correct: 1,
    explanation: "SCA limits government/third-party provider access; party-to-party discovery in litigation follows civil procedure and privilege rules.",
  },
  {
    id: "q-23",
    domain: "II",
    question: "The Dodd-Frank Act transferred many consumer financial protection duties to:",
    options: ["FERPA office", "Consumer Financial Protection Bureau (CFPB)", "FDA", "OSHA"],
    correct: 1,
    explanation: "CFPB enforces consumer financial protection laws including aspects of FCRA and other consumer finance rules.",
  },
  {
    id: "q-24",
    domain: "V",
    question: "A 'cure period' in some state privacy laws allows businesses to:",
    options: [
      "Ignore all violations permanently",
      "Remedy certain violations within a defined time after notice before penalties",
      "Sell data without consent",
      "Avoid all privacy notices",
    ],
    correct: 1,
    explanation: "Cure periods give businesses opportunity to fix violations after regulator or consumer notice before fines apply, where provided.",
  },
  {
    id: "q-25",
    domain: "I",
    question: "Vendor management in a privacy program should include:",
    options: [
      "No written agreements",
      "Due diligence, contracts with privacy/security terms, and ongoing monitoring",
      "Only verbal assurances",
      "Delegating all accountability to the vendor",
    ],
    correct: 1,
    explanation: "Effective vendor management includes risk assessment, DPAs/contracts, subprocessors, audits, and breach notification obligations.",
  },
];

export function getDomainById(id) {
  return DOMAINS.find((d) => d.id === id);
}

export function getAllCards() {
  return [...FLASHCARDS];
}

export function getCardsByDomain(domainId) {
  if (!domainId || domainId === "all") return FLASHCARDS;
  return FLASHCARDS.filter((c) => c.domain === domainId);
}

export function getQuizByDomain(domainId, count = 10) {
  let pool = domainId && domainId !== "all"
    ? QUIZ_QUESTIONS.filter((q) => q.domain === domainId)
    : [...QUIZ_QUESTIONS];
  pool = shuffle(pool);
  return pool.slice(0, Math.min(count, pool.length));
}

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
